# Generated by Django 5.1.2 on 2024-12-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_num', models.IntegerField(default=0)),
                ('comment', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('del_comment', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'polls_comments',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
